static const char gnu_project_script[] =
"\"\"\"A real offline GNU project build run inside the protected PRoot process tree.\"\"\"\n"
"import ctypes\n"
"import errno\n"
"import hashlib\n"
"import json\n"
"import os\n"
"from pathlib import Path\n"
"import socket\n"
"import subprocess\n"
"import sys\n"
"\n"
"assert os.getuid() != 0\n"
"libc = ctypes.CDLL(None, use_errno=True)\n"
"libc.prctl.restype = ctypes.c_int\n"
"assert libc.prctl(39, 0, 0, 0, 0) == 1, 'Actual no_new_privs must remain enabled'\n"
"assert libc.prctl(21, 0, 0, 0, 0) == 2, 'Native seccomp filter must remain installed'\n"
"\n"
"denials = []\n"
"for name, action in (\n"
"    ('outside-file-read', lambda: Path('/outside/victim.txt').read_bytes()),\n"
"    ('workspace-symlink-outside-read', lambda: Path('/foldgpt-fixture/outside-link/victim.txt').read_bytes()),\n"
"    ('actual-proc-environment-read', lambda: Path('/proc/self/environ').read_bytes()),\n"
"    ('outside-file-write', lambda: Path('/outside/victim.txt').write_text('forbidden')),\n"
"    ('outside-mode-change', lambda: os.chmod('/outside/victim.txt', 0o777)),\n"
"    ('external-network-socket', lambda: socket.socket(socket.AF_INET, socket.SOCK_STREAM)),\n"
"):\n"
"    try:\n"
"        result = action()\n"
"    except OSError as error:\n"
"        assert error.errno in (errno.EACCES, errno.EPERM), (name, error)\n"
"        denials.append({'name': name, 'errno': error.errno})\n"
"    else:\n"
"        raise RuntimeError(f'Required kernel protection did not deny {name}: {result!r}')\n"
"\n"
"ctypes.set_errno(0)\n"
"assert libc.unshare(0x40000000) == -1 and ctypes.get_errno() == errno.EPERM, 'Network namespace denied by inherited filter'\n"
"denials.append({'name':'network-namespace-unshare', 'errno':ctypes.get_errno()})\n"
"ctypes.set_errno(0)\n"
"assert libc.prctl(4, 0, 0, 0, 0) == -1 and ctypes.get_errno() == errno.EOPNOTSUPP, 'Strict PRoot must report unsupported dumpability protection honestly'\n"
"denials.append({'name':'unsupported-pr-set-dumpable', 'errno':ctypes.get_errno()})\n"
"\n"
"project = Path('/tmp/project')\n"
"project.mkdir(mode=0o700)\n"
"(project/'dist').mkdir(mode=0o700)\n"
"(project/'app').mkdir(mode=0o700)\n"
"(project/'app'/'maths.py').write_text('def doubled(value):\\n    return value + value\\n')\n"
"(project/'app'/'__main__.py').write_text('from maths import doubled\\nprint(f\"native GNU project: {doubled(21)}\")\\n')\n"
"(project/'test_maths.py').write_text('''import sys\n"
"import unittest\n"
"sys.path.insert(0, 'app')\n"
"from maths import doubled\n"
"class MathsTests(unittest.TestCase):\n"
"    def test_positive(self): self.assertEqual(doubled(21), 42)\n"
"    def test_zero(self): self.assertEqual(doubled(0), 0)\n"
"    def test_negative(self): self.assertEqual(doubled(-8), -16)\n"
"if __name__ == '__main__': unittest.main()\n"
"''')\n"
"# Bash and GNU Python are real guest ELF executables, launched through strict\n"
"# PRoot. The source edit, bytecode compilation, tests, package and execution are\n"
"# recorded as actual artifacts in the physical scratch directory.\n"
"script = '''set -euo pipefail\n"
"test \"$PWD\" = /tmp/project\n"
"python3 -c \"from pathlib import Path; p=Path('app/maths.py'); p.write_text(p.read_text().replace('value + value', 'value * 2'))\"\n"
"python3 -m py_compile app/maths.py app/__main__.py test_maths.py\n"
"python3 -m unittest discover -v\n"
"python3 -m zipapp app -o dist/app.pyz\n"
"python3 dist/app.pyz > dist/result.txt\n"
"python3 -c \"from pathlib import Path; assert Path('dist/result.txt').read_text() == 'native GNU project: 42\\\\n'\"\n"
"'''\n"
"result = subprocess.run(['/bin/bash', '-c', script], cwd=project, text=True, capture_output=True, timeout=40)\n"
"(project/'build.stdout').write_text(result.stdout)\n"
"(project/'build.stderr').write_text(result.stderr)\n"
"if result.returncode:\n"
"    print(result.stdout, end='')\n"
"    print(result.stderr, file=sys.stderr, end='')\n"
"    raise RuntimeError(f'Actual GNU project build failed: {result.returncode}')\n"
"assert 'Ran 3 tests' in result.stderr and '\\nOK\\n' in result.stderr\n"
"assert (project/'dist/result.txt').read_text() == 'native GNU project: 42\\n'\n"
"assert 'value * 2' in (project/'app/maths.py').read_text()\n"
"assert (project/'dist/app.pyz').read_bytes().startswith(b'PK')\n"
"nonzero = subprocess.run(['/bin/bash', '-c', 'exit 23'], capture_output=True)\n"
"assert nonzero.returncode == 23, nonzero.returncode\n"
"report = {'status':'PASS', 'uid':os.getuid(), 'python':sys.version, 'machine':os.uname().machine,\n"
"          'tests':3, 'buildExit':result.returncode, 'nonzeroExit':nonzero.returncode, 'denials':denials,\n"
"          'artifacts':{str(p.relative_to(project)):hashlib.sha256(p.read_bytes()).hexdigest()\n"
"                       for p in sorted(project.rglob('*')) if p.is_file()}}\n"
"(project/'report.json').write_text(json.dumps(report, indent=2)+'\\n')\n"
"print(json.dumps({'status':'PASS', 'project':'/tmp/project', 'tests':3, 'denials':len(denials)}))\n";
