cmake_minimum_required(VERSION 3.22.1)
project(foldgpt_install C)
add_library(foldgpt-install SHARED install-files.c)
target_compile_features(foldgpt-install PRIVATE c_std_11)
target_compile_options(foldgpt-install PRIVATE -Wall -Wextra -Werror -fstack-protector-strong)
target_link_options(foldgpt-install PRIVATE -Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384)
