pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }
rootProject.name = 'FoldGPTShizukuLab'
include ':app'
include ':shizukuTransport'
project(':shizukuTransport').projectDir = file('../shizuku-service/transport')
